### ISSUE TITLE
AllowedContent side effect

### ISSUE THREAD

**Issue by b3nkai** [connecta-ag/t3footnotes#3]
Hi !

We have a little side effect using t3footnotes extension : the ckeditor now allow everythings, evety tags, classes, attributes, ...
Usefull features like code cleaning when copy-paste from MS Word is totaly disabled.

This is due to this directive :

```
editor:
  config:
    allowedContent = true
```

This is not really a good idea to allow everything. For these extension usage, you can replace that with this configuration :

```
editor:
  config:
    extraAllowedContent: 'span[!class]{display}(t3foonotes-anchor-data); sup(t3foonote); a[id](t3foonotes-anchor);'
```

This will do the job and keep ckeditor cleaning working.

You should also think to remove the "display: none" style attribute by managing this with a css. In this case we also can remove the "{display}" configuration in extraAllowedContent :

```
editor:
  externalPlugins:
    t3footnotes:
      resource: "EXT:t3footnotes/Resources/Public/JavaScript/Plugins/t3footnotes/"
  config:
    extraAllowedContent: 'span[!class](t3foonotes-anchor-data); sup(t3foonote); a[id](t3foonotes-anchor);'
    contentsCss: "EXT:t3footnotes/Resources/Public/Css/ckeditor.css"
```

With Resources/Public/Css/ckeditor.css file containing :

`.t3foonotes-anchor-data { display: none; }`

And update documentation to inform about these configurations which can be incompatible with specific projects' configurations.

Regards,
Benoit
